importScripts("precache-manifest.a18340914dca2da7188732c82c09b7ac.js", "https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js");

// manifest import and workbox imports will be autogenerated by webpack
workbox.precaching.precacheAndRoute(self.__precacheManifest || []);
